"""empty message

Revision ID: 0379dd9ca2d3
Revises: 
Create Date: 2025-02-26 11:39:06.730438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0379dd9ca2d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balsa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('capacidade_maxima', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('peso_medio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balsa_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('quantidade_veiculos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['balsa_id'], ['balsa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_travessia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viagem_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_travessia')
    op.drop_table('viagem')
    op.drop_table('veiculo')
    op.drop_table('balsa')
    # ### end Alembic commands ###
